apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins  # Указание namespace
spec:
  type: NodePort                       # Используем NodePort для доступа с хоста
  ports:
    - port: 8080                       # Внутренний порт
      targetPort: 8080                 # Порт Jenkins в контейнере
      nodePort: 32000                  # Порт, который будет открыт на локальной машине
  selector:
    app: jenkins