apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 10Gi  # Укажите нужный объем
  accessModes:
    - ReadWriteOnce  # Режим доступа
  hostPath:
    path: /var/lib/docker/volumes/Jenkins/_data  # Путь к Docker Volume